### ISSUE TITLE
Does not handle apt:// URL

### ISSUE THREAD

**Issue by bootloop2dope** [Ferk/apt-linker#1]
Still wants to open with xdg-open.

I restarted the browser, logged out, restarted and still handles apt:// URL with xdg-open.

I only got this to handle apt:// URLs with Chrome...

Debian Jessie (Q4OS derivative)

apturl is installed.

And it does not work. Clicked on an apt-get link... got

Malformed URL:
apt:

This Chrome extension does not work.

**Comment by Ferk** [comment]
It's expected for it to open with xdg-open, but xdg-open should know how to handle the links.

Your operative system doesn't appear to have apt-url support. You are probably missing the apt-url package (it's probably not installed by default in Debian Jessie).

See this for Debian: https://wiki.debian.org/AptProtocol

The purpose of this extension is simply to replace `apt-get install blahblah` lines with apt:// links. The links do not work by themselves if you do not have the right programs installed to open them, since otherwise it's not possible to do this in the browser.
